[server]
maxUploadSize = 500
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
fastReruns = true

[client]
toolbarMode = "minimal"
showErrorDetails = true

[theme]
base = "dark"
